### ISSUE TITLE
Introducción a Ember Data

### ISSUE THREAD

**Issue by rubenmoya** [embermadrid/talks#1]
**Título de la charla:**
Introducción a Ember Data

**Descripción:**
Qué es Ember Data, cómo funciona, cómo crear modelos, cómo crear relaciones entre modelos, adapters...

**Etiqueta:** Help wanted! :)

**Comment by Serabe** [comment]
Yo cambiaría adapters (un tema complejo de por sí) por transforms (más simples y muy útiles también, aunque menos conocidas).

**Comment by Serabe** [comment]
[¡Anunciada!](http://www.meetup.com/Ember-js-Madrid/events/221129908/)
